name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          architecture: 'x64'

      - name: Run unit tests
        run: |
          # Add commands to build and run your Java unit tests
          ./gradlew test  # Example command for Gradle projects
